import{expect,test}from"@playwright/test";

test("Arabic default and English routes render",async({page})=>{await page.goto("/");await expect(page.locator("html")).toHaveAttribute("dir","rtl");await expect(page.getByRole("heading",{level:1})).toContainText("تمويلي");await page.goto("/en");await expect(page.locator("html")).toHaveAttribute("dir","ltr");await expect(page.getByRole("heading",{level:1})).toContainText("financing decision")});

for(const persona of ["ahmed_borderline","sara_strong","khalid_rejected"]){test(`Arabic journey completes analysis and offers for ${persona}`,async({page})=>{await page.goto("/journey");await page.locator("select").first().selectOption(persona);await page.getByRole("button",{name:"حلّل قدرتي"}).click();await expect(page).toHaveURL(/journey\/analysis/,{timeout:30000});await expect(page.getByRole("heading",{level:2})).toContainText("صورتك المالية");await page.getByRole("link",{name:"العروض"}).click();await expect(page.getByRole("heading",{level:2})).toContainText("العروض مرتبة");await expect(page.getByText("سعر غير مؤكد").first()).toBeVisible()})}

test("English journey reaches a simulated application",async({page})=>{await page.goto("/en/journey");await page.locator("select").first().selectOption("sara_strong");await page.getByRole("button",{name:"Analyze affordability"}).click();await expect(page).toHaveURL(/\/en\/journey\/analysis/,{timeout:30000});await page.getByRole("link",{name:"Offers"}).click();await expect(page.getByText("Unverified rate").first()).toBeVisible();await page.getByRole("link",{name:"Decision"}).click();await expect(page.getByText("Simulation only").first()).toBeVisible();await page.getByRole("button",{name:"Start simulated application"}).click();await expect(page.getByText("draft",{exact:true})).toBeVisible()});

test("status degrades or renders live data",async({page})=>{await page.goto("/status");await expect(page.getByRole("heading",{level:2})).toContainText("حالة");await expect(page.getByText(/offers|الاتصال/).first()).toBeVisible({timeout:15000})});
